export interface WindTurbineSpec {
  rated_mw: number;
  rotor_diameter_m: number;
  swept_area_m2?: number;
  hub_height_range_m?: string;
  iec_class?: string;
  cut_in_ws_ms?: number;
  rated_ws_ms?: number;
  cut_out_ws_ms?: number;
  drivetrain?: string;
  generator?: string;
  source_url?: string;
}

export interface SolarModuleSpec {
  power_wp: number;
  technology: string;
  cell_type?: string;
  module_efficiency_pct?: number;
  bifaciality_pct?: number;
  temp_coeff_pmax_pct_per_c?: number;
  temp_coeff_voc_pct_per_c?: number;
  temp_coeff_isc_pct_per_c?: number;
  first_year_degradation_pct?: number;
  annual_degradation_pct?: number;
  length_mm?: number;
  width_mm?: number;
  thickness_mm?: number;
  weight_kg?: number;
  max_system_voltage_v?: number;
  operating_temp_min_c?: number;
  operating_temp_max_c?: number;
  glass_description?: string;
  frame_description?: string;
  source_url?: string;
}

export interface SolarInverterSpec {
  ac_kw: number;
  max_efficiency_pct?: number;
  european_efficiency_pct?: number;
  mppt_count?: number;
  max_dc_voltage_v?: number;
  startup_voltage_v?: number;
  operating_temp_min_c?: number;
  operating_temp_max_c?: number;
  protection_rating?: string;
  communication?: string;
  source_url?: string;
}

export interface BessContainerSpec {
  power_mw: number;
  energy_mwh: number;
  duration_hours: number;
  cost_eur_kwh?: number;
  footprint_m2?: number;
  area_with_access_m2?: number;
  battery_containers_20ft?: number;
  pcs_transformer_skids_40ft?: number;
  deployment_notes?: string;
  chemistry?: string;
  round_trip_efficiency_pct?: number;
  cycle_life?: string;
  cooling?: string;
  enclosure_rating?: string;
  fire_suppression?: string;
  operating_temp_min_c?: number;
  operating_temp_max_c?: number;
  source_url?: string;
}

export const WIND_TURBINE_KB = {
  Vestas: {
    "V136-4.5": {
      rated_mw: 4.5,
      rotor_diameter_m: 136,
      swept_area_m2: 14527,
      hub_height_range_m: "82-166",
      iec_class: "IEC S / IEC IIIA",
      cut_in_ws_ms: 3,
      rated_ws_ms: 12,
      cut_out_ws_ms: 25,
      drivetrain: "Geared",
      generator: "DFIG",
      source_url: "https://www.vestas.com/en/products/4-mw-platform/v136-4-5-mw",
    },
    "V150-4.5": {
      rated_mw: 4.5,
      rotor_diameter_m: 150,
      swept_area_m2: 17671,
      hub_height_range_m: "105-166",
      iec_class: "IEC IIIA",
      cut_in_ws_ms: 3,
      rated_ws_ms: 11.5,
      cut_out_ws_ms: 25,
      drivetrain: "Geared",
      generator: "DFIG",
      source_url: "https://www.vestas.com/en/products/enventus-platform/v150-4-5-mw",
    },
    "V162-6.2": {
      rated_mw: 6.2,
      rotor_diameter_m: 162,
      swept_area_m2: 20612,
      hub_height_range_m: "119-166",
      iec_class: "IEC S / IEC IIA",
      cut_in_ws_ms: 3,
      rated_ws_ms: 10.5,
      cut_out_ws_ms: 25,
      drivetrain: "Geared",
      generator: "DFIG",
      source_url: "https://www.vestas.com/en/products/enventus-platform/v162-6-2-mw",
    },
    "V172-7.2": {
      rated_mw: 7.2,
      rotor_diameter_m: 172,
      swept_area_m2: 23226,
      hub_height_range_m: "127-199",
      iec_class: "IEC S",
      cut_in_ws_ms: 3,
      rated_ws_ms: 10,
      cut_out_ws_ms: 25,
      drivetrain: "Geared",
      generator: "DFIG",
      source_url: "https://www.vestas.com/en/products/enventus-platform/v172-7-2-mw",
    },
  },
  "Siemens Gamesa": {
    "SG 5.0-145": {
      rated_mw: 5.0,
      rotor_diameter_m: 145,
      swept_area_m2: 16513,
      hub_height_range_m: "102.5-127.5",
      iec_class: "IEC II / IEC III",
      cut_in_ws_ms: 3,
      rated_ws_ms: 11.5,
      cut_out_ws_ms: 25,
      drivetrain: "Geared",
      generator: "DFIG",
      source_url: "https://www.siemensgamesa.com/en-int/products-and-services/onshore/wind-turbine-sg-5-0-145",
    },
    "SG 6.6-170": {
      rated_mw: 6.6,
      rotor_diameter_m: 170,
      swept_area_m2: 22700,
      hub_height_range_m: "115-165",
      iec_class: "IEC IIA / IEC IIIA",
      cut_in_ws_ms: 3,
      rated_ws_ms: 11,
      cut_out_ws_ms: 25,
      drivetrain: "Geared",
      generator: "DFIG",
      source_url: "https://www.siemensgamesa.com/en-int/products-and-services/onshore/sg-6-6-170",
    },
    "SG 7.0-170": {
      rated_mw: 7.0,
      rotor_diameter_m: 170,
      swept_area_m2: 22700,
      hub_height_range_m: "115-165",
      iec_class: "IEC II / IEC III",
      cut_in_ws_ms: 3,
      rated_ws_ms: 10.5,
      cut_out_ws_ms: 25,
      drivetrain: "Geared",
      generator: "DFIG",
      source_url: "https://www.siemensgamesa.com/global/en/home/products-and-services/onshore.html",
    },
  },
  "GE Vernova": {
    "GE 4.8-158": {
      rated_mw: 4.8,
      rotor_diameter_m: 158,
      swept_area_m2: 19607,
      hub_height_range_m: "101-161",
      iec_class: "IEC S",
      cut_in_ws_ms: 3,
      rated_ws_ms: 11,
      cut_out_ws_ms: 25,
      drivetrain: "Geared",
      generator: "DFIG",
      source_url: "https://www.gevernova.com/wind/onshore-wind/turbines/cypress-platform",
    },
    "GE 6.1-158": {
      rated_mw: 6.1,
      rotor_diameter_m: 158,
      swept_area_m2: 19607,
      hub_height_range_m: "101-161",
      iec_class: "IEC S",
      cut_in_ws_ms: 3,
      rated_ws_ms: 10.5,
      cut_out_ws_ms: 25,
      drivetrain: "Geared",
      generator: "DFIG",
      source_url: "https://www.gevernova.com/wind/onshore-wind/turbines/cypress-platform",
    },
  },
  Enercon: {
    "E-138 EP3": {
      rated_mw: 4.26,
      rotor_diameter_m: 138,
      swept_area_m2: 14957,
      hub_height_range_m: "81-160",
      iec_class: "IEC S",
      cut_in_ws_ms: 2.5,
      rated_ws_ms: 12,
      cut_out_ws_ms: 28,
      drivetrain: "Direct drive",
      generator: "EESG",
      source_url: "https://www.enercon.de/en/products/ep-3/e-138-ep3",
    },
    "E-160 EP5": {
      rated_mw: 5.56,
      rotor_diameter_m: 160,
      swept_area_m2: 20106,
      hub_height_range_m: "120-166",
      iec_class: "IEC S",
      cut_in_ws_ms: 2.5,
      rated_ws_ms: 11.5,
      cut_out_ws_ms: 34,
      drivetrain: "Direct drive",
      generator: "EESG",
      source_url: "https://www.enercon.de/en/products/ep-5/e-160-ep5",
    },
    "E-175 EP5": {
      rated_mw: 6.0,
      rotor_diameter_m: 175,
      swept_area_m2: 24053,
      hub_height_range_m: "162-179",
      iec_class: "IEC S",
      cut_in_ws_ms: 2.5,
      rated_ws_ms: 10.5,
      cut_out_ws_ms: 34,
      drivetrain: "Direct drive",
      generator: "EESG",
      source_url: "https://www.enercon.de/en/products/ep-5/e-175-ep5",
    },
  },
  Nordex: {
    "N149/4.5": {
      rated_mw: 4.5,
      rotor_diameter_m: 149,
      swept_area_m2: 17460,
      hub_height_range_m: "105-164",
      iec_class: "IEC S",
      cut_in_ws_ms: 3,
      rated_ws_ms: 11,
      cut_out_ws_ms: 25,
      drivetrain: "Geared",
      generator: "DFIG",
      source_url: "https://www.nordex-online.com/en/product/n149-4-x/",
    },
    "N163/5.X": {
      rated_mw: 5.9,
      rotor_diameter_m: 163,
      swept_area_m2: 20867,
      hub_height_range_m: "118-164",
      iec_class: "IEC S",
      cut_in_ws_ms: 3,
      rated_ws_ms: 10.5,
      cut_out_ws_ms: 25,
      drivetrain: "Geared",
      generator: "DFIG",
      source_url: "https://www.nordex-online.com/en/product/n163-5-x/",
    },
    "N175/6.X": {
      rated_mw: 6.8,
      rotor_diameter_m: 175,
      swept_area_m2: 24053,
      hub_height_range_m: "112-179",
      iec_class: "IEC S",
      cut_in_ws_ms: 3,
      rated_ws_ms: 10,
      cut_out_ws_ms: 25,
      drivetrain: "Geared",
      generator: "DFIG",
      source_url: "https://www.nordex-online.com/en/2022/09/new-rotor-for-the-energy-transition-nordex-group-presents-the-n175-6-x/",
    },
  },
} as const satisfies Record<string, Record<string, WindTurbineSpec>>;

export const SOLAR_MODULE_KB = {
  "First Solar": {
    "Series 7 TR1": {
      power_wp: 535,
      technology: "CdTe thin-film",
      cell_type: "Thin-film CdTe",
      module_efficiency_pct: 19.3,
      temp_coeff_pmax_pct_per_c: -0.28,
      temp_coeff_voc_pct_per_c: -0.24,
      temp_coeff_isc_pct_per_c: 0.04,
      first_year_degradation_pct: 1.0,
      annual_degradation_pct: 0.3,
      length_mm: 2009,
      width_mm: 1232,
      thickness_mm: 35,
      weight_kg: 34.4,
      max_system_voltage_v: 1500,
      operating_temp_min_c: -40,
      operating_temp_max_c: 85,
      glass_description: "Heat strengthened front and rear glass",
      frame_description: "Anodized aluminum frame",
      source_url: "https://www.firstsolar.com/en/Modules/Series-7",
    },
    "Series 6 CuRe": {
      power_wp: 480,
      technology: "CdTe thin-film",
      cell_type: "Thin-film CdTe",
      module_efficiency_pct: 19.3,
      temp_coeff_pmax_pct_per_c: -0.28,
      temp_coeff_voc_pct_per_c: -0.24,
      temp_coeff_isc_pct_per_c: 0.04,
      annual_degradation_pct: 0.3,
      length_mm: 2008,
      width_mm: 1232,
      thickness_mm: 35,
      weight_kg: 34.5,
      max_system_voltage_v: 1500,
      operating_temp_min_c: -40,
      operating_temp_max_c: 85,
      glass_description: "Heat strengthened front and rear glass",
      frame_description: "Anodized aluminum frame",
      source_url: "https://www.firstsolar.com/en/lp/SEA",
    },
    "Series 6 Plus Bifacial": {
      power_wp: 485,
      technology: "CdTe thin-film bifacial",
      cell_type: "Thin-film CdTe",
      module_efficiency_pct: 19.5,
      bifaciality_pct: 80,
      temp_coeff_pmax_pct_per_c: -0.28,
      temp_coeff_voc_pct_per_c: -0.24,
      temp_coeff_isc_pct_per_c: 0.04,
      annual_degradation_pct: 0.3,
      length_mm: 2008,
      width_mm: 1232,
      thickness_mm: 35,
      weight_kg: 35.0,
      max_system_voltage_v: 1500,
      operating_temp_min_c: -40,
      operating_temp_max_c: 85,
      glass_description: "Heat strengthened front and rear glass",
      frame_description: "Anodized aluminum frame",
      source_url: "https://www.firstsolar.com/en/lp/SEA",
    },
    "Series 6 Plus": {
      power_wp: 460,
      technology: "CdTe thin-film",
      cell_type: "Thin-film CdTe",
      module_efficiency_pct: 18.2,
      temp_coeff_pmax_pct_per_c: -0.28,
      temp_coeff_voc_pct_per_c: -0.24,
      temp_coeff_isc_pct_per_c: 0.04,
      first_year_degradation_pct: 1.0,
      annual_degradation_pct: 0.3,
      length_mm: 2008,
      width_mm: 1232,
      thickness_mm: 35,
      weight_kg: 34.5,
      max_system_voltage_v: 1500,
      operating_temp_min_c: -40,
      operating_temp_max_c: 85,
      glass_description: "Heat strengthened front and rear glass",
      frame_description: "Anodized aluminum frame",
      source_url: "https://www.firstsolar.com/en/Modules/Series-6-Plus",
    },
  },
  "Jinko Solar": {
    "Tiger Neo 72HL4-BDV": {
      power_wp: 585,
      technology: "N-type TOPCon bifacial",
      cell_type: "182 mm N-type mono TOPCon",
      module_efficiency_pct: 22.65,
      bifaciality_pct: 80,
      temp_coeff_pmax_pct_per_c: -0.29,
      temp_coeff_voc_pct_per_c: -0.25,
      temp_coeff_isc_pct_per_c: 0.045,
      first_year_degradation_pct: 1.0,
      annual_degradation_pct: 0.4,
      length_mm: 2278,
      width_mm: 1134,
      thickness_mm: 30,
      weight_kg: 32,
      max_system_voltage_v: 1500,
      operating_temp_min_c: -40,
      operating_temp_max_c: 85,
      glass_description: "2.0 mm heat strengthened dual glass",
      frame_description: "Anodized aluminum alloy",
      source_url: "https://jinkosolar.eu/wp-content/uploads/2023/04/JKM565N-585N-72HL4-BDV-F4-EN.pdf",
    },
    "Tiger Neo 78HL4-BDV": {
      power_wp: 635,
      technology: "N-type TOPCon bifacial",
      cell_type: "182 mm N-type mono TOPCon",
      module_efficiency_pct: 22.7,
      bifaciality_pct: 80,
      temp_coeff_pmax_pct_per_c: -0.29,
      temp_coeff_voc_pct_per_c: -0.25,
      temp_coeff_isc_pct_per_c: 0.045,
      first_year_degradation_pct: 1.0,
      annual_degradation_pct: 0.4,
      length_mm: 2465,
      width_mm: 1134,
      thickness_mm: 30,
      weight_kg: 34.0,
      max_system_voltage_v: 1500,
      operating_temp_min_c: -40,
      operating_temp_max_c: 85,
      glass_description: "Dual glass bifacial module",
      frame_description: "Anodized aluminum alloy",
      source_url: "https://jinkosolar.eu/wp-content/uploads/2023/08/JKM605N-635N-78HL4-BDV-F5-EN.pdf",
    },
    "Neo Green 78HL4-BDV": {
      power_wp: 650,
      technology: "N-type TOPCon bifacial",
      cell_type: "182 mm N-type mono TOPCon",
      module_efficiency_pct: 23.2,
      bifaciality_pct: 80,
      temp_coeff_pmax_pct_per_c: -0.29,
      temp_coeff_voc_pct_per_c: -0.25,
      temp_coeff_isc_pct_per_c: 0.045,
      first_year_degradation_pct: 1.0,
      annual_degradation_pct: 0.4,
      length_mm: 2465,
      width_mm: 1134,
      thickness_mm: 30,
      weight_kg: 34.5,
      max_system_voltage_v: 1500,
      operating_temp_min_c: -40,
      operating_temp_max_c: 85,
      glass_description: "Dual glass bifacial module",
      frame_description: "Anodized aluminum alloy",
      source_url: "https://jinkosolar.eu/wp-content/uploads/2023/08/JKM605N-635N-78HL4-BDV-F5-EN.pdf",
    },
    "Tiger Pro 72HC": {
      power_wp: 540,
      technology: "Mono PERC",
      cell_type: "182 mm mono PERC",
      module_efficiency_pct: 20.93,
      temp_coeff_pmax_pct_per_c: -0.35,
      temp_coeff_voc_pct_per_c: -0.28,
      temp_coeff_isc_pct_per_c: 0.048,
      first_year_degradation_pct: 2.0,
      annual_degradation_pct: 0.55,
      length_mm: 2274,
      width_mm: 1134,
      thickness_mm: 35,
      weight_kg: 28.9,
      max_system_voltage_v: 1500,
      operating_temp_min_c: -40,
      operating_temp_max_c: 85,
      glass_description: "3.2 mm AR coated tempered glass",
      frame_description: "Anodized aluminum alloy",
      source_url: "https://jinkosolar.eu/wp-content/uploads/2021/01/JKM520M-540M-72HL4-V-F1-EN.pdf",
    },
  },
  LONGi: {
    "Hi-MO 7 LR7-72HGD": {
      power_wp: 615,
      technology: "HPDC bifacial",
      cell_type: "N-type HPDC",
      module_efficiency_pct: 22.8,
      bifaciality_pct: 80,
      temp_coeff_pmax_pct_per_c: -0.28,
      temp_coeff_voc_pct_per_c: -0.23,
      temp_coeff_isc_pct_per_c: 0.045,
      first_year_degradation_pct: 1.0,
      annual_degradation_pct: 0.4,
      length_mm: 2382,
      width_mm: 1134,
      thickness_mm: 30,
      weight_kg: 33.5,
      max_system_voltage_v: 1500,
      operating_temp_min_c: -40,
      operating_temp_max_c: 85,
      glass_description: "2.0 + 2.0 mm semi-tempered dual glass",
      frame_description: "Anodized aluminum alloy",
      source_url: "https://www.longi.com/en/products/modules/utility-scale/hi-mo-7/",
    },
    "Hi-MO 9 LR7-72HYD": {
      power_wp: 670,
      technology: "HPBC 2.0 bifacial",
      cell_type: "Back-contact HPBC 2.0",
      module_efficiency_pct: 24.8,
      bifaciality_pct: 80,
      temp_coeff_pmax_pct_per_c: -0.26,
      first_year_degradation_pct: 1.0,
      annual_degradation_pct: 0.35,
      length_mm: 2382,
      width_mm: 1134,
      thickness_mm: 30,
      weight_kg: 33.5,
      max_system_voltage_v: 1500,
      operating_temp_min_c: -40,
      operating_temp_max_c: 85,
      glass_description: "Dual glass module",
      frame_description: "Anodized aluminum alloy",
      source_url: "https://www.longi.com/en/news/upgrade-hi-mo-9-launch/",
    },
    "Hi-MO X10 LR7-72HVD": {
      power_wp: 670,
      technology: "HPBC 2.0 back-contact",
      cell_type: "Back-contact HPBC 2.0",
      module_efficiency_pct: 24.8,
      temp_coeff_pmax_pct_per_c: -0.24,
      first_year_degradation_pct: 1.0,
      annual_degradation_pct: 0.35,
      length_mm: 2382,
      width_mm: 1134,
      thickness_mm: 30,
      weight_kg: 33.5,
      max_system_voltage_v: 1500,
      operating_temp_min_c: -40,
      operating_temp_max_c: 85,
      glass_description: "Dual glass back-contact module",
      frame_description: "Anodized aluminum alloy",
      source_url: "https://eu.longi.com/pt/press/intersolar-2025-longi-is-a-finalist-for-the-smarter-e-award-2025-in-the-category-photovoltaics-with-its-hi-mo-x10-back-contact-module",
    },
    "Hi-MO 5 LR5-72HPH": {
      power_wp: 545,
      technology: "Mono PERC",
      cell_type: "182 mm mono PERC",
      module_efficiency_pct: 21.3,
      temp_coeff_pmax_pct_per_c: -0.34,
      temp_coeff_voc_pct_per_c: -0.265,
      temp_coeff_isc_pct_per_c: 0.05,
      first_year_degradation_pct: 2.0,
      annual_degradation_pct: 0.55,
      length_mm: 2256,
      width_mm: 1133,
      thickness_mm: 35,
      weight_kg: 27.2,
      max_system_voltage_v: 1500,
      operating_temp_min_c: -40,
      operating_temp_max_c: 85,
      glass_description: "3.2 mm tempered glass",
      frame_description: "Anodized aluminum alloy",
      source_url: "https://www.longi.com/en/products/modules/hi-mo-5/",
    },
  },
  "JA Solar": {
    "DeepBlue 4.0 Pro JAM72D40": {
      power_wp: 585,
      technology: "N-type bifacial",
      cell_type: "N-type mono",
      module_efficiency_pct: 22.6,
      bifaciality_pct: 80,
      temp_coeff_pmax_pct_per_c: -0.30,
      temp_coeff_voc_pct_per_c: -0.26,
      temp_coeff_isc_pct_per_c: 0.046,
      first_year_degradation_pct: 1.0,
      annual_degradation_pct: 0.4,
      length_mm: 2333,
      width_mm: 1134,
      thickness_mm: 30,
      weight_kg: 32.5,
      max_system_voltage_v: 1500,
      operating_temp_min_c: -40,
      operating_temp_max_c: 85,
      glass_description: "Dual glass",
      frame_description: "Anodized aluminum alloy",
      source_url: "https://www.jasolar.com/html/en/products/2023/0221/1821.html",
    },
    "DeepBlue 4.0 Pro JAM72D42/LB": {
      power_wp: 650,
      technology: "N-type TOPCon bifacial",
      cell_type: "N-type mono TOPCon",
      module_efficiency_pct: 23.3,
      bifaciality_pct: 80,
      temp_coeff_pmax_pct_per_c: -0.29,
      temp_coeff_voc_pct_per_c: -0.245,
      temp_coeff_isc_pct_per_c: 0.045,
      first_year_degradation_pct: 1.0,
      annual_degradation_pct: 0.4,
      length_mm: 2382,
      width_mm: 1134,
      thickness_mm: 30,
      weight_kg: 33.1,
      max_system_voltage_v: 1500,
      operating_temp_min_c: -40,
      operating_temp_max_c: 85,
      glass_description: "Dual glass TOPCon module",
      frame_description: "Anodized aluminum alloy",
      source_url: "https://www.jasolar.com/uploadfile/fujian/2025/0427/52d33dc829fb8d0.pdf",
    },
    "DeepBlue 4.0 Pro JAM72D40/MB": {
      power_wp: 605,
      technology: "N-type TOPCon",
      cell_type: "N-type mono TOPCon",
      module_efficiency_pct: 22.4,
      temp_coeff_pmax_pct_per_c: -0.29,
      temp_coeff_voc_pct_per_c: -0.245,
      temp_coeff_isc_pct_per_c: 0.045,
      first_year_degradation_pct: 1.0,
      annual_degradation_pct: 0.4,
      length_mm: 2278,
      width_mm: 1134,
      thickness_mm: 30,
      weight_kg: 31.8,
      max_system_voltage_v: 1500,
      operating_temp_min_c: -40,
      operating_temp_max_c: 85,
      glass_description: "Tempered glass frontsheet",
      frame_description: "Anodized aluminum alloy",
      source_url: "https://www.jasolar.com/uploadfile/fujian/2025/0427/52d33dc829fb8d0.pdf",
    },
    JAM72S30: {
      power_wp: 545,
      technology: "Mono PERC",
      cell_type: "11BB mono PERC",
      module_efficiency_pct: 21.1,
      temp_coeff_pmax_pct_per_c: -0.35,
      temp_coeff_voc_pct_per_c: -0.275,
      temp_coeff_isc_pct_per_c: 0.045,
      first_year_degradation_pct: 2.0,
      annual_degradation_pct: 0.55,
      length_mm: 2278,
      width_mm: 1134,
      thickness_mm: 35,
      weight_kg: 28.6,
      max_system_voltage_v: 1500,
      operating_temp_min_c: -40,
      operating_temp_max_c: 85,
      glass_description: "3.2 mm tempered glass",
      frame_description: "Anodized aluminum alloy",
      source_url: "https://www.jasolar.com/uploadfile/2021/0909/20210909045959319.pdf",
    },
  },
  "Canadian Solar": {
    "TOPBiHiKu6 CS6W": {
      power_wp: 620,
      technology: "TOPCon bifacial",
      cell_type: "N-type TOPCon",
      module_efficiency_pct: 22.95,
      bifaciality_pct: 80,
      temp_coeff_pmax_pct_per_c: -0.29,
      temp_coeff_voc_pct_per_c: -0.25,
      temp_coeff_isc_pct_per_c: 0.045,
      first_year_degradation_pct: 1.0,
      annual_degradation_pct: 0.4,
      length_mm: 2384,
      width_mm: 1303,
      thickness_mm: 33,
      weight_kg: 38.7,
      max_system_voltage_v: 1500,
      operating_temp_min_c: -40,
      operating_temp_max_c: 85,
      glass_description: "Dual glass",
      frame_description: "Anodized aluminum alloy",
      source_url: "https://www.csisolar.com/solution/topbihiku6/",
    },
    "TOPBiHiKu7 CS7N": {
      power_wp: 725,
      technology: "N-type TOPCon bifacial",
      cell_type: "210 mm N-type TOPCon",
      module_efficiency_pct: 23.3,
      bifaciality_pct: 85,
      temp_coeff_pmax_pct_per_c: -0.29,
      temp_coeff_voc_pct_per_c: -0.25,
      temp_coeff_isc_pct_per_c: 0.05,
      first_year_degradation_pct: 1.0,
      annual_degradation_pct: 0.4,
      length_mm: 2384,
      width_mm: 1303,
      thickness_mm: 33,
      weight_kg: 38.3,
      max_system_voltage_v: 1500,
      operating_temp_min_c: -40,
      operating_temp_max_c: 85,
      glass_description: "Dual glass",
      frame_description: "Anodized aluminum alloy",
      source_url: "https://www.csisolar.com/solution/topbihiku7/",
    },
    "HiKu7 CS7L": {
      power_wp: 600,
      technology: "Mono PERC",
      cell_type: "210 mm mono PERC",
      module_efficiency_pct: 21.4,
      temp_coeff_pmax_pct_per_c: -0.34,
      temp_coeff_voc_pct_per_c: -0.26,
      temp_coeff_isc_pct_per_c: 0.05,
      first_year_degradation_pct: 2.0,
      annual_degradation_pct: 0.55,
      length_mm: 2172,
      width_mm: 1303,
      thickness_mm: 35,
      weight_kg: 31.0,
      max_system_voltage_v: 1500,
      operating_temp_min_c: -40,
      operating_temp_max_c: 85,
      glass_description: "3.2 mm tempered glass",
      frame_description: "Anodized aluminum alloy",
      source_url: "https://www.csisolar.com/solution/hiku7/",
    },
  },
  "Trina Solar": {
    "Vertex N TSM-NEG19RC": {
      power_wp: 615,
      technology: "N-type i-TOPCon bifacial",
      cell_type: "N-type i-TOPCon",
      module_efficiency_pct: 22.8,
      bifaciality_pct: 80,
      temp_coeff_pmax_pct_per_c: -0.29,
      temp_coeff_voc_pct_per_c: -0.24,
      temp_coeff_isc_pct_per_c: 0.04,
      first_year_degradation_pct: 1.0,
      annual_degradation_pct: 0.4,
      length_mm: 2384,
      width_mm: 1134,
      thickness_mm: 30,
      weight_kg: 33.7,
      max_system_voltage_v: 1500,
      operating_temp_min_c: -40,
      operating_temp_max_c: 85,
      glass_description: "Dual glass",
      frame_description: "Anodized aluminum alloy",
      source_url: "https://www.trinasolar.com/eu-en/product/vertex-n",
    },
    "Vertex N TSM-NEG21C.20": {
      power_wp: 740,
      technology: "N-type i-TOPCon bifacial",
      cell_type: "210 mm N-type i-TOPCon",
      module_efficiency_pct: 23.8,
      bifaciality_pct: 80,
      temp_coeff_pmax_pct_per_c: -0.29,
      temp_coeff_voc_pct_per_c: -0.24,
      temp_coeff_isc_pct_per_c: 0.04,
      first_year_degradation_pct: 1.0,
      annual_degradation_pct: 0.4,
      length_mm: 2384,
      width_mm: 1303,
      thickness_mm: 33,
      weight_kg: 38.3,
      max_system_voltage_v: 1500,
      operating_temp_min_c: -40,
      operating_temp_max_c: 85,
      glass_description: "Dual glass",
      frame_description: "Anodized aluminum alloy",
      source_url: "https://www.trinasolar.com/en-apac/NEG21C.20/",
    },
    "Vertex TSM-DE18M": {
      power_wp: 540,
      technology: "Mono PERC",
      cell_type: "210 mm mono PERC",
      module_efficiency_pct: 21.2,
      temp_coeff_pmax_pct_per_c: -0.34,
      temp_coeff_voc_pct_per_c: -0.25,
      temp_coeff_isc_pct_per_c: 0.04,
      first_year_degradation_pct: 2.0,
      annual_degradation_pct: 0.55,
      length_mm: 2384,
      width_mm: 1096,
      thickness_mm: 35,
      weight_kg: 28.6,
      max_system_voltage_v: 1500,
      operating_temp_min_c: -40,
      operating_temp_max_c: 85,
      glass_description: "3.2 mm tempered glass",
      frame_description: "Anodized aluminum alloy",
      source_url: "https://www.trinasolar.com/eu-en/product/vertex",
    },
  },
} as const satisfies Record<string, Record<string, SolarModuleSpec>>;

export const SOLAR_INVERTER_KB = {
  Sungrow: {
    SG250HX: {
      ac_kw: 250,
      max_efficiency_pct: 99.0,
      european_efficiency_pct: 98.8,
      mppt_count: 12,
      max_dc_voltage_v: 1500,
      startup_voltage_v: 550,
      operating_temp_min_c: -30,
      operating_temp_max_c: 60,
      protection_rating: "IP66",
      communication: "PLC / RS485 / optional Wi-Fi",
      source_url: "https://en.sungrowpower.com/productDetail/1920/sg250hx",
    },
    "SG3125HV-MV": {
      ac_kw: 3125,
      max_efficiency_pct: 99.0,
      european_efficiency_pct: 98.9,
      mppt_count: 30,
      max_dc_voltage_v: 1500,
      startup_voltage_v: 875,
      operating_temp_min_c: -35,
      operating_temp_max_c: 60,
      protection_rating: "IP65",
      communication: "Ethernet / RS485 / PLC",
      source_url: "https://en.sungrowpower.com/productDetail/1919/sg3125hv-mv",
    },
  },
  Huawei: {
    "SUN2000-100KTL-M1": {
      ac_kw: 100,
      max_efficiency_pct: 98.8,
      european_efficiency_pct: 98.6,
      mppt_count: 10,
      max_dc_voltage_v: 1100,
      startup_voltage_v: 200,
      operating_temp_min_c: -25,
      operating_temp_max_c: 60,
      protection_rating: "IP66",
      communication: "MBUS / RS485 / WLAN / 4G",
      source_url: "https://solar.huawei.com/en/products/smart-pv-controller/sun2000-100ktl-m1",
    },
    "SUN2000-330KTL-H1": {
      ac_kw: 330,
      max_efficiency_pct: 99.0,
      european_efficiency_pct: 98.8,
      mppt_count: 6,
      max_dc_voltage_v: 1500,
      startup_voltage_v: 500,
      operating_temp_min_c: -25,
      operating_temp_max_c: 60,
      protection_rating: "IP66",
      communication: "PLC / MBUS / RS485 / WLAN / 4G",
      source_url: "https://solar.huawei.com/en/products/smart-pv-controller/sun2000-330ktl-h1",
    },
  },
  SMA: {
    "Sunny Tripower CORE2 110": {
      ac_kw: 110,
      max_efficiency_pct: 98.6,
      european_efficiency_pct: 98.4,
      mppt_count: 12,
      max_dc_voltage_v: 1100,
      startup_voltage_v: 250,
      operating_temp_min_c: -25,
      operating_temp_max_c: 60,
      protection_rating: "IP66",
      communication: "Ethernet / Webconnect / Modbus",
      source_url: "https://www.sma.de/en/products/solar-inverters/sunny-tripower-core2",
    },
    "Sunny Central 2475-EV": {
      ac_kw: 2475,
      max_efficiency_pct: 98.8,
      european_efficiency_pct: 98.6,
      max_dc_voltage_v: 1500,
      startup_voltage_v: 875,
      operating_temp_min_c: -25,
      operating_temp_max_c: 50,
      protection_rating: "IP54",
      communication: "Ethernet / Modbus / SMA Data Manager",
      source_url: "https://www.sma.de/en/products/solar-inverters/sunny-central-ev",
    },
  },
  "ABB / FIMER": {
    "PVS-250-TL": {
      ac_kw: 250,
      max_efficiency_pct: 99.0,
      european_efficiency_pct: 98.8,
      mppt_count: 12,
      max_dc_voltage_v: 1500,
      startup_voltage_v: 860,
      operating_temp_min_c: -25,
      operating_temp_max_c: 60,
      protection_rating: "IP66",
      communication: "RS485 / Ethernet / Modbus",
      source_url: "https://www.fimer.com/pvs-250-tl",
    },
    "PVS-980-TL": {
      ac_kw: 980,
      max_efficiency_pct: 98.9,
      european_efficiency_pct: 98.7,
      max_dc_voltage_v: 1500,
      startup_voltage_v: 875,
      operating_temp_min_c: -25,
      operating_temp_max_c: 60,
      protection_rating: "IP65",
      communication: "RS485 / Ethernet / Modbus",
      source_url: "https://www.fimer.com/pvs-980-tl",
    },
  },
  Delta: {
    MH250HV: {
      ac_kw: 250,
      max_efficiency_pct: 99.0,
      european_efficiency_pct: 98.8,
      mppt_count: 12,
      max_dc_voltage_v: 1500,
      startup_voltage_v: 900,
      operating_temp_min_c: -30,
      operating_temp_max_c: 60,
      protection_rating: "IP66",
      communication: "PLC / RS485 / Ethernet",
      source_url: "https://www.delta-emea.com/en-GB/products/Solar-Inverter/ALL/24791",
    },
    "RPI H5A": {
      ac_kw: 550,
      max_efficiency_pct: 98.9,
      european_efficiency_pct: 98.7,
      max_dc_voltage_v: 1500,
      startup_voltage_v: 875,
      operating_temp_min_c: -25,
      operating_temp_max_c: 60,
      protection_rating: "IP54",
      communication: "Ethernet / RS485 / Modbus",
      source_url: "https://www.delta-emea.com/en-GB/products/Solar-Inverter/ALL/24789",
    },
  },
  Fronius: {
    "Tauro ECO 100-3-P": {
      ac_kw: 100,
      max_efficiency_pct: 98.5,
      european_efficiency_pct: 98.2,
      mppt_count: 6,
      max_dc_voltage_v: 1000,
      startup_voltage_v: 200,
      operating_temp_min_c: -25,
      operating_temp_max_c: 60,
      protection_rating: "IP66",
      communication: "Fronius Solar.web / Modbus / SunSpec",
      source_url: "https://www.fronius.com/en/solar-energy/installers-partners/technical-data/all-products/inverters/fronius-tauro/fronius-tauro-eco-100-3-p",
    },
    "Symo Advanced 20.0-3-M": {
      ac_kw: 20,
      max_efficiency_pct: 98.0,
      european_efficiency_pct: 97.7,
      mppt_count: 2,
      max_dc_voltage_v: 1000,
      startup_voltage_v: 200,
      operating_temp_min_c: -25,
      operating_temp_max_c: 60,
      protection_rating: "IP66",
      communication: "Fronius Solar.web / Modbus",
      source_url: "https://www.fronius.com/en/solar-energy/installers-partners/technical-data/all-products/inverters/fronius-symo-advanced/fronius-symo-advanced-20-0-3-m",
    },
  },
  "Power Electronics": {
    "FS1500CU": {
      ac_kw: 1500,
      max_efficiency_pct: 99.0,
      european_efficiency_pct: 98.8,
      max_dc_voltage_v: 1500,
      startup_voltage_v: 875,
      operating_temp_min_c: -25,
      operating_temp_max_c: 55,
      protection_rating: "IP54",
      communication: "Ethernet / Modbus / SunSpec",
      source_url: "https://powerelectronics.com/products/solar-inverters/",
    },
    "SC500CP": {
      ac_kw: 500,
      max_efficiency_pct: 98.8,
      european_efficiency_pct: 98.6,
      max_dc_voltage_v: 1500,
      startup_voltage_v: 650,
      operating_temp_min_c: -25,
      operating_temp_max_c: 55,
      protection_rating: "IP55",
      communication: "Ethernet / RS485 / Modbus",
      source_url: "https://powerelectronics.com/products/solar-inverters/",
    },
  },
  SolarEdge: {
    "SE166K": {
      ac_kw: 166,
      max_efficiency_pct: 99.2,
      european_efficiency_pct: 99.0,
      mppt_count: 1,
      max_dc_voltage_v: 1500,
      startup_voltage_v: 680,
      operating_temp_min_c: -40,
      operating_temp_max_c: 60,
      protection_rating: "IP66",
      communication: "RS485 / Ethernet / SolarEdge Cloud",
      source_url: "https://www.solaredge.com/en/products/commercial-inverters",
    },
    "SE250K": {
      ac_kw: 250,
      max_efficiency_pct: 99.0,
      european_efficiency_pct: 98.8,
      mppt_count: 1,
      max_dc_voltage_v: 1500,
      startup_voltage_v: 680,
      operating_temp_min_c: -40,
      operating_temp_max_c: 60,
      protection_rating: "IP65",
      communication: "RS485 / Ethernet / SolarEdge Cloud",
      source_url: "https://www.solaredge.com/en/products/commercial-inverters",
    },
  },
  KACO: {
    "blueplanet 150 TL3": {
      ac_kw: 150,
      max_efficiency_pct: 98.7,
      european_efficiency_pct: 98.5,
      mppt_count: 4,
      max_dc_voltage_v: 1100,
      startup_voltage_v: 250,
      operating_temp_min_c: -25,
      operating_temp_max_c: 60,
      protection_rating: "IP65",
      communication: "RS485 / Ethernet / Modbus",
      source_url: "https://kaco-newenergy.com/products/solar-inverters/",
    },
    "XP500U-TL": {
      ac_kw: 500,
      max_efficiency_pct: 98.7,
      european_efficiency_pct: 98.5,
      max_dc_voltage_v: 1000,
      startup_voltage_v: 430,
      operating_temp_min_c: -25,
      operating_temp_max_c: 50,
      protection_rating: "IP54",
      communication: "Ethernet / Modbus",
      source_url: "https://kaco-newenergy.com/products/solar-inverters/",
    },
  },
} as const satisfies Record<string, Record<string, SolarInverterSpec>>;

export const BESS_CONTAINER_KB = {
  Tesla: {
    "Megapack 2": {
      power_mw: 1.9,
      energy_mwh: 3.9,
      duration_hours: 2.0,
      cost_eur_kwh: 200,
      footprint_m2: 11.9,
      area_with_access_m2: 52,
      chemistry: "LFP",
      round_trip_efficiency_pct: 92,
      cycle_life: "Utility-duty design life up to 20 years",
      cooling: "Liquid cooling",
      enclosure_rating: "Outdoor utility enclosure",
      fire_suppression: "Integrated fire detection and suppression architecture",
      operating_temp_min_c: -30,
      operating_temp_max_c: 50,
      source_url: "https://www.tesla.com/megapack",
    },
    "Megapack 2 XL": {
      power_mw: 1.9,
      energy_mwh: 3.9,
      duration_hours: 2.05,
      cost_eur_kwh: 200,
      footprint_m2: 14.5,
      area_with_access_m2: 52,
      chemistry: "LFP",
      round_trip_efficiency_pct: 92,
      cycle_life: "Utility-duty design life up to 20 years",
      cooling: "Liquid cooling",
      enclosure_rating: "Outdoor utility enclosure",
      fire_suppression: "Integrated fire detection and suppression architecture",
      operating_temp_min_c: -30,
      operating_temp_max_c: 50,
      source_url: "https://www.tesla.com/megapack",
    },
  },
  Sungrow: {
    "PowerTitan 2.0": {
      power_mw: 5.0,
      energy_mwh: 10.0,
      duration_hours: 2.0,
      cost_eur_kwh: 200,
      footprint_m2: 14.9,
      area_with_access_m2: 120,
      chemistry: "LFP",
      round_trip_efficiency_pct: 90,
      cycle_life: "Long-life utility-scale LFP platform",
      cooling: "Liquid cooling",
      enclosure_rating: "IP55 battery enclosure / C5 corrosion protection",
      fire_suppression: "Electricity isolated protection and aerosol/fire protection",
      operating_temp_min_c: -30,
      operating_temp_max_c: 55,
      source_url: "https://en.sungrowpower.com/productDetail/2750/PowerTitan-2.0",
    },
    "PowerTitan ST2752UX": {
      power_mw: 1.725,
      energy_mwh: 2.752,
      duration_hours: 1.6,
      cost_eur_kwh: 200,
      footprint_m2: 14.9,
      area_with_access_m2: 60,
      chemistry: "LFP",
      round_trip_efficiency_pct: 89,
      cycle_life: "Utility-scale LFP platform",
      cooling: "Liquid cooling",
      enclosure_rating: "Outdoor utility enclosure",
      fire_suppression: "Integrated fire detection and suppression",
      operating_temp_min_c: -30,
      operating_temp_max_c: 55,
      source_url: "https://en.sungrowpower.com/productDetail/1675/ST2752UX",
    },
  },
  Fluence: {
    "Gridstack Pro": {
      power_mw: 2.8,
      energy_mwh: 5.6,
      duration_hours: 2.0,
      cost_eur_kwh: 200,
      footprint_m2: 14.9,
      area_with_access_m2: 90,
      chemistry: "LFP",
      round_trip_efficiency_pct: 90,
      cycle_life: "High-throughput grid application platform",
      cooling: "Liquid cooling",
      enclosure_rating: "Outdoor grid-scale enclosure",
      fire_suppression: "Fluence safety architecture with early gas detection",
      operating_temp_min_c: -20,
      operating_temp_max_c: 50,
      source_url: "https://fluenceenergy.com/products/gridstack-pro/",
    },
  },
  CATL: {
    "EnerC Plus": {
      power_mw: 1.0,
      energy_mwh: 3.72,
      duration_hours: 3.72,
      cost_eur_kwh: 200,
      footprint_m2: 14.9,
      area_with_access_m2: 70,
      chemistry: "LFP",
      round_trip_efficiency_pct: 95,
      cycle_life: "Up to 10,000 cycles",
      cooling: "Liquid cooling",
      enclosure_rating: "Outdoor containerized system",
      fire_suppression: "Integrated fire suppression and thermal management",
      operating_temp_min_c: -30,
      operating_temp_max_c: 55,
      source_url: "https://www.catl.com/en/solution/ess/",
    },
    TENER: {
      power_mw: 3.125,
      energy_mwh: 6.25,
      duration_hours: 2.0,
      cost_eur_kwh: 200,
      footprint_m2: 14.9,
      area_with_access_m2: 80,
      chemistry: "LFP",
      round_trip_efficiency_pct: 95,
      cycle_life: "Five-year zero degradation claim / long-life utility platform",
      cooling: "Liquid cooling",
      enclosure_rating: "20-foot containerized ESS",
      fire_suppression: "All-round safety architecture with thermal management integration",
      operating_temp_min_c: -30,
      operating_temp_max_c: 55,
      source_url: "https://www.catl.com/en/news/6232.html",
    },
    "TENER Stack": {
      power_mw: 4.5,
      energy_mwh: 9.0,
      duration_hours: 2.0,
      cost_eur_kwh: 200,
      footprint_m2: 14.9,
      area_with_access_m2: 75,
      chemistry: "LFP",
      round_trip_efficiency_pct: 95,
      cycle_life: "High-density utility storage architecture",
      cooling: "Liquid cooling",
      enclosure_rating: "High-density utility ESS enclosure",
      fire_suppression: "Integrated fire suppression and thermal management",
      operating_temp_min_c: -30,
      operating_temp_max_c: 55,
      source_url: "https://www.catl.com/en/news/6232.html",
    },
  },
  HiTHIUM: {
    "∞Power 6.25MWh 4h": {
      power_mw: 1.563,
      energy_mwh: 6.25,
      duration_hours: 4.0,
      cost_eur_kwh: 200,
      footprint_m2: 14.8,
      area_with_access_m2: 82,
      chemistry: "LFP",
      round_trip_efficiency_pct: 95,
      cycle_life: "Long-duration utility-scale storage platform",
      cooling: "Liquid cooling",
      enclosure_rating: "Containerized ESS enclosure",
      fire_suppression: "Integrated thermal management and safety architecture",
      operating_temp_min_c: -30,
      operating_temp_max_c: 55,
      source_url: "https://en.hithium.com/newsroom/latest/details/86.html",
    },
    "∞Power 6.25MWh 2h": {
      power_mw: 3.125,
      energy_mwh: 6.25,
      duration_hours: 2.0,
      cost_eur_kwh: 200,
      footprint_m2: 14.8,
      area_with_access_m2: 82,
      chemistry: "LFP",
      round_trip_efficiency_pct: 95,
      cycle_life: "High-density utility-scale storage platform",
      cooling: "Liquid cooling",
      enclosure_rating: "Containerized ESS enclosure",
      fire_suppression: "Integrated thermal management and safety architecture",
      operating_temp_min_c: -30,
      operating_temp_max_c: 55,
      source_url: "https://en.hithium.com/newsroom/latest/details/86.html",
    },
  },
  Wärtsilä: {
    Quantum: {
      power_mw: 1.0,
      energy_mwh: 2.0,
      duration_hours: 2.0,
      cost_eur_kwh: 200,
      footprint_m2: 7.4,
      area_with_access_m2: 65,
      chemistry: "LFP",
      round_trip_efficiency_pct: 88,
      cycle_life: "Grid-scale long-life storage platform",
      cooling: "Liquid cooling",
      enclosure_rating: "Outdoor modular enclosure",
      fire_suppression: "GridSolv Quantum safety and suppression system",
      operating_temp_min_c: -20,
      operating_temp_max_c: 50,
      source_url: "https://www.wartsila.com/energy/storage/gridsolv-quantum",
    },
  },
  "Connected Energy": {
    "M-STOR 4.35 MW / 2.6 h": {
      power_mw: 4.35,
      energy_mwh: 11.31,
      duration_hours: 2.6,
      cost_eur_kwh: 200,
      footprint_m2: 163,
      area_with_access_m2: 391,
      battery_containers_20ft: 9,
      pcs_transformer_skids_40ft: 1,
      deployment_notes: "Deployed as battery containers plus separate PCS and transformer skid",
      chemistry: "Second-life EV battery system",
      round_trip_efficiency_pct: 84,
      cycle_life: "Modular industrial-scale second-life storage architecture",
      cooling: "Air cooling",
      enclosure_rating: "Outdoor utility-scale containerized system",
      fire_suppression: "Integrated battery management and thermal event protection architecture",
      operating_temp_min_c: -10,
      operating_temp_max_c: 45,
      source_url: "https://www.connected.energy",
    },
    "M-STOR 4.35 MW / 3.5 h": {
      power_mw: 4.35,
      energy_mwh: 15.225,
      duration_hours: 3.5,
      cost_eur_kwh: 200,
      footprint_m2: 207,
      area_with_access_m2: 497,
      battery_containers_20ft: 12,
      pcs_transformer_skids_40ft: 1,
      deployment_notes: "Deployed as battery containers plus separate PCS and transformer skid",
      chemistry: "Second-life EV battery system",
      round_trip_efficiency_pct: 84,
      cycle_life: "Modular industrial-scale second-life storage architecture",
      cooling: "Air cooling",
      enclosure_rating: "Outdoor utility-scale containerized system",
      fire_suppression: "Integrated battery management and thermal event protection architecture",
      operating_temp_min_c: -10,
      operating_temp_max_c: 45,
      source_url: "https://www.connected.energy",
    },
    "M-STOR 5.8 MW / 2.6 h": {
      power_mw: 5.8,
      energy_mwh: 15.08,
      duration_hours: 2.6,
      cost_eur_kwh: 200,
      footprint_m2: 207,
      area_with_access_m2: 497,
      battery_containers_20ft: 12,
      pcs_transformer_skids_40ft: 1,
      deployment_notes: "Deployed as battery containers plus separate PCS and transformer skid",
      chemistry: "Second-life EV battery system",
      round_trip_efficiency_pct: 84,
      cycle_life: "Modular industrial-scale second-life storage architecture",
      cooling: "Air cooling",
      enclosure_rating: "Outdoor utility-scale containerized system",
      fire_suppression: "Integrated battery management and thermal event protection architecture",
      operating_temp_min_c: -10,
      operating_temp_max_c: 45,
      source_url: "https://www.connected.energy",
    },
    "M-STOR 5.8 MW / 3.5 h": {
      power_mw: 5.8,
      energy_mwh: 20.3,
      duration_hours: 3.5,
      cost_eur_kwh: 200,
      footprint_m2: 266,
      area_with_access_m2: 638,
      battery_containers_20ft: 16,
      pcs_transformer_skids_40ft: 1,
      deployment_notes: "Deployed as battery containers plus separate PCS and transformer skid",
      chemistry: "Second-life EV battery system",
      round_trip_efficiency_pct: 84,
      cycle_life: "Modular industrial-scale second-life storage architecture",
      cooling: "Air cooling",
      enclosure_rating: "Outdoor utility-scale containerized system",
      fire_suppression: "Integrated battery management and thermal event protection architecture",
      operating_temp_min_c: -10,
      operating_temp_max_c: 45,
      source_url: "https://www.connected.energy",
    },
    "M-STOR 8.7 MW / 2.6 h": {
      power_mw: 8.7,
      energy_mwh: 22.62,
      duration_hours: 2.6,
      cost_eur_kwh: 200,
      footprint_m2: 325,
      area_with_access_m2: 780,
      battery_containers_20ft: 18,
      pcs_transformer_skids_40ft: 2,
      deployment_notes: "Deployed as battery containers plus separate PCS and transformer skid",
      chemistry: "Second-life EV battery system",
      round_trip_efficiency_pct: 84,
      cycle_life: "Modular industrial-scale second-life storage architecture",
      cooling: "Air cooling",
      enclosure_rating: "Outdoor utility-scale containerized system",
      fire_suppression: "Integrated battery management and thermal event protection architecture",
      operating_temp_min_c: -10,
      operating_temp_max_c: 45,
      source_url: "https://www.connected.energy",
    },
    "M-STOR 8.7 MW / 3.5 h": {
      power_mw: 8.7,
      energy_mwh: 30.45,
      duration_hours: 3.5,
      cost_eur_kwh: 200,
      footprint_m2: 414,
      area_with_access_m2: 994,
      battery_containers_20ft: 24,
      pcs_transformer_skids_40ft: 2,
      deployment_notes: "Deployed as battery containers plus separate PCS and transformer skid",
      chemistry: "Second-life EV battery system",
      round_trip_efficiency_pct: 84,
      cycle_life: "Modular industrial-scale second-life storage architecture",
      cooling: "Air cooling",
      enclosure_rating: "Outdoor utility-scale containerized system",
      fire_suppression: "Integrated battery management and thermal event protection architecture",
      operating_temp_min_c: -10,
      operating_temp_max_c: 45,
      source_url: "https://www.connected.energy",
    },
    "M-STOR 11.6 MW / 2.6 h": {
      power_mw: 11.6,
      energy_mwh: 30.16,
      duration_hours: 2.6,
      cost_eur_kwh: 200,
      footprint_m2: 384,
      area_with_access_m2: 922,
      battery_containers_20ft: 24,
      pcs_transformer_skids_40ft: 1,
      deployment_notes: "Deployed as battery containers plus separate PCS and transformer skid",
      chemistry: "Second-life EV battery system",
      round_trip_efficiency_pct: 84,
      cycle_life: "Modular industrial-scale second-life storage architecture",
      cooling: "Air cooling",
      enclosure_rating: "Outdoor utility-scale containerized system",
      fire_suppression: "Integrated battery management and thermal event protection architecture",
      operating_temp_min_c: -10,
      operating_temp_max_c: 45,
      source_url: "https://www.connected.energy",
    },
    "M-STOR 11.6 MW / 3.5 h": {
      power_mw: 11.6,
      energy_mwh: 40.6,
      duration_hours: 3.5,
      cost_eur_kwh: 200,
      footprint_m2: 532,
      area_with_access_m2: 1277,
      battery_containers_20ft: 32,
      pcs_transformer_skids_40ft: 2,
      deployment_notes: "Deployed as battery containers plus separate PCS and transformer skid",
      chemistry: "Second-life EV battery system",
      round_trip_efficiency_pct: 84,
      cycle_life: "Modular industrial-scale second-life storage architecture",
      cooling: "Air cooling",
      enclosure_rating: "Outdoor utility-scale containerized system",
      fire_suppression: "Integrated battery management and thermal event protection architecture",
      operating_temp_min_c: -10,
      operating_temp_max_c: 45,
      source_url: "https://www.connected.energy",
    },
  },
} as const satisfies Record<string, Record<string, BessContainerSpec>>;

type WindManufacturer = keyof typeof WIND_TURBINE_KB;
type SolarModuleManufacturer = keyof typeof SOLAR_MODULE_KB;
type SolarInverterManufacturer = keyof typeof SOLAR_INVERTER_KB;
type BessManufacturer = keyof typeof BESS_CONTAINER_KB;

export function getWindManufacturers() {
  return Object.keys(WIND_TURBINE_KB) as WindManufacturer[];
}

export function getWindModels(manufacturer: string) {
  return Object.keys(WIND_TURBINE_KB[manufacturer as WindManufacturer] ?? {});
}

export function getWindSpec(manufacturer: string, model: string) {
  return WIND_TURBINE_KB[manufacturer as WindManufacturer]?.[model as keyof (typeof WIND_TURBINE_KB)[WindManufacturer]] as
    | WindTurbineSpec
    | undefined;
}

export function getSolarModuleManufacturers() {
  return Object.keys(SOLAR_MODULE_KB) as SolarModuleManufacturer[];
}

export function getSolarModuleModels(manufacturer: string) {
  return Object.keys(SOLAR_MODULE_KB[manufacturer as SolarModuleManufacturer] ?? {});
}

export function getSolarModuleSpec(manufacturer: string, model: string) {
  return SOLAR_MODULE_KB[manufacturer as SolarModuleManufacturer]?.[model as keyof (typeof SOLAR_MODULE_KB)[SolarModuleManufacturer]] as
    | SolarModuleSpec
    | undefined;
}

export function getSolarInverterManufacturers() {
  return Object.keys(SOLAR_INVERTER_KB) as SolarInverterManufacturer[];
}

export function getSolarInverterModels(manufacturer: string) {
  return Object.keys(SOLAR_INVERTER_KB[manufacturer as SolarInverterManufacturer] ?? {});
}

export function getSolarInverterSpec(manufacturer: string, model: string) {
  return SOLAR_INVERTER_KB[manufacturer as SolarInverterManufacturer]?.[model as keyof (typeof SOLAR_INVERTER_KB)[SolarInverterManufacturer]] as
    | SolarInverterSpec
    | undefined;
}

export function getBessManufacturers() {
  return Object.keys(BESS_CONTAINER_KB) as BessManufacturer[];
}

export function getBessModels(manufacturer: string) {
  return Object.keys(BESS_CONTAINER_KB[manufacturer as BessManufacturer] ?? {});
}

export function getBessSpec(manufacturer: string, model: string) {
  return BESS_CONTAINER_KB[manufacturer as BessManufacturer]?.[model as keyof (typeof BESS_CONTAINER_KB)[BessManufacturer]] as
    | BessContainerSpec
    | undefined;
}

function includesNormalized(haystack: string, needle: string) {
  return haystack.toLowerCase().includes(needle.toLowerCase().split("/")[0].trim());
}

export function detectWindManufacturer(value: string) {
  const normalized = value.toLowerCase();
  return getWindManufacturers().find((manufacturer) => normalized.includes(manufacturer.toLowerCase())) ?? "";
}

export function detectSolarModuleManufacturer(value: string) {
  return getSolarModuleManufacturers().find((manufacturer) => includesNormalized(value, manufacturer)) ?? "";
}

export function detectSolarInverterManufacturer(value: string) {
  return getSolarInverterManufacturers().find((manufacturer) => includesNormalized(value, manufacturer)) ?? "";
}

export function detectBessManufacturer(value: string) {
  return getBessManufacturers().find((manufacturer) => includesNormalized(value, manufacturer)) ?? "";
}
